const SEED_DATA =
[
  {
    "id": "b001",
    "title": "Just Another Spiritual Book",
    "author": "Bo Lozoff",
    "genre": "Philosophy",
    "yearPublished": 1990,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 5,
    "favorite": true,
    "tags": [],
    "recommendedBy": "",
    "notes": "Absolutely incredible book. Letters from prisoners that show forgiveness, growth, compassion.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b002",
    "title": "Who is Michael Ovitz?",
    "author": "Michael Ovitz",
    "genre": "Biography",
    "yearPublished": 2018,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 5,
    "favorite": true,
    "tags": [],
    "recommendedBy": "Chamath",
    "notes": "Chamath said \"it's an incredible book\" on All in Pod. Founder of CAA.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b003",
    "title": "The War of Art",
    "author": "Steven Pressfield",
    "genre": "Self-Help",
    "yearPublished": 2002,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 5,
    "favorite": true,
    "tags": [],
    "recommendedBy": "Joe Rogan",
    "notes": "Great book. Joe Rogan gives this book to everybody.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b004",
    "title": "A Visit from the Goon Squad",
    "author": "Jennifer Egan",
    "genre": "Novel",
    "yearPublished": 2010,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Dr. Jain",
    "notes": "Dr. Jain noted that she was reading this. Teens in band in the 80s, trials and tribulations as they get old.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b005",
    "title": "Klara and the Sun",
    "author": "Kazuo Ishiguro",
    "genre": "Novel",
    "yearPublished": 2021,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 5,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Dr. Jain",
    "notes": "Recommended by Dr. Jain. Great book.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b006",
    "title": "The $12 million stuffed shark",
    "author": "Donald N. Thompson",
    "genre": "Non-Fiction",
    "yearPublished": 2008,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL16819694M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "A book about the contemporary art market.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b007",
    "title": "Read Write Own",
    "author": "Chris Dixon",
    "genre": "Technology",
    "yearPublished": 2024,
    "pageCount": null,
    "coverImage": "https://m.media-amazon.com/images/I/7178aDXQe6L._SL1500_.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b008",
    "title": "The Limehouse Golem",
    "author": "Peter Ackroyd",
    "genre": "Novel",
    "yearPublished": 2012,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Bought before going to London. Great read.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b009",
    "title": "How to Live an Extraordinary Life",
    "author": "Anthony Pompliano",
    "genre": "Personal Development",
    "yearPublished": 2024,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b010",
    "title": "The Creative Act",
    "author": "Rick Rubin",
    "genre": "Creativity",
    "yearPublished": 2023,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL38208363M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b011",
    "title": "Acid for the Children",
    "author": "Flea (Michael Balzary)",
    "genre": "Biography",
    "yearPublished": 2019,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b012",
    "title": "Surrender: 40 Songs, One Story",
    "author": "Bono",
    "genre": "Biography",
    "yearPublished": 2022,
    "pageCount": null,
    "coverImage": "https://m.media-amazon.com/images/I/91QpEI6zWEL._SL1500_.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b013",
    "title": "Mother of God",
    "author": "Paul Rosolie",
    "genre": "Biography",
    "yearPublished": 2014,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b014",
    "title": "The House of Medici: Its Rise and Fall",
    "author": "Christopher Hibbert",
    "genre": "History",
    "yearPublished": 1974,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Bought before going to Florence. Finished afterwards.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b015",
    "title": "A Cook's Tour",
    "author": "Anthony Bourdain",
    "genre": "Travel",
    "yearPublished": 2001,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL7274528M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b016",
    "title": "In a Sunburned Country",
    "author": "Bill Bryson",
    "genre": "Travel",
    "yearPublished": 2000,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Sheenagh",
    "notes": "Purchased before Australia trip. One of Sheenagh's fav authors.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b017",
    "title": "The Deadly Donut",
    "author": "Ana T. Drew",
    "genre": "Novel",
    "yearPublished": 2020,
    "pageCount": null,
    "coverImage": "https://m.media-amazon.com/images/I/61u+pVhNfnL._SL1500_.jpg",
    "format": "Digital/Kindle",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Kindle ad",
    "notes": "Recommended on Kindle. Ads work.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b018",
    "title": "Sum: Forty Tales from the Afterlives",
    "author": "David Eagleman",
    "genre": "Fiction",
    "yearPublished": 2009,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Patrick Collison",
    "notes": "From Patrick Collison's booklist.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b019",
    "title": "Co-Intelligence",
    "author": "Ethan Mollick",
    "genre": "Non-Fiction",
    "yearPublished": 2024,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL50620808M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b020",
    "title": "The Science of Rapid Skill Acquisition",
    "author": "Peter Hollins",
    "genre": "Personal Development",
    "yearPublished": 2019,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Pomp",
    "notes": "Recommended by Pomp.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b021",
    "title": "Read Your Own Mind",
    "author": "Oz Pearlman",
    "genre": "Personal Development",
    "yearPublished": 2025,
    "pageCount": null,
    "coverImage": "https://m.media-amazon.com/images/I/71-XQbZ1TZL._SL1500_.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b022",
    "title": "Hits, Flops, and Other Illusions",
    "author": "Ed Zwick",
    "genre": "Biography",
    "yearPublished": 2024,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Ed Zwick's memoir about Hollywood directing, producing, and writing.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b023",
    "title": "Weird Scenes Inside The Canyon",
    "author": "David McGowan",
    "genre": "History",
    "yearPublished": 2014,
    "pageCount": null,
    "coverImage": "https://m.media-amazon.com/images/I/51+qwK5xb9L.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Marc Andreessen",
    "notes": "Marc Andreessen talked about it. Wild book.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b024",
    "title": "The Alchemist",
    "author": "Paulo Coelho",
    "genre": "Fiction",
    "yearPublished": 1988,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "I thought it was 'meh.' Maybe I should read again one day.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b025",
    "title": "The 4-Hour Workweek",
    "author": "Tim Ferriss",
    "genre": "Business",
    "yearPublished": 2009,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Groundbreaking at the time. But now over-hyped. Read it in 2010.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b026",
    "title": "The Lean Startup",
    "author": "Eric Ries",
    "genre": "Business",
    "yearPublished": 2011,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 2,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Meh. Over hyped. Good tips but life and business not predictable.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b027",
    "title": "Rumsfeld",
    "author": "Midge Decter",
    "genre": "Business",
    "yearPublished": 2003,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL3689983M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 1,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "I gave this book one star on Amazon.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b028",
    "title": "Moloka'i",
    "author": "Alan Brennert",
    "genre": "Novel",
    "yearPublished": 2003,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (Used)",
    "status": "reading",
    "datePurchased": "",
    "dateStarted": "2025-09-09",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Started 9/9/2025",
    "description": "",
    "dateAdded": "2025-09-01"
  },
  {
    "id": "b029",
    "title": "The Technological Republic",
    "author": "Alexander Karp",
    "genre": "Non-Fiction",
    "yearPublished": 2025,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "reading",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b030",
    "title": "Web3: Charting the Internet's Next Economic and Cultural Frontier",
    "author": "Alex Tapscott",
    "genre": "Technology",
    "yearPublished": 2023,
    "pageCount": null,
    "coverImage": "https://m.media-amazon.com/images/I/71FLMMe7UDL._SL1500_.jpg",
    "format": "Digital/Kindle",
    "status": "reading",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b031",
    "title": "Founders",
    "author": "Jimmy Soni",
    "genre": "Non-Fiction",
    "yearPublished": 2021,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL37795462M-M.jpg",
    "format": "Physical (New)",
    "status": "on-hold",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [
      "gifted to me"
    ],
    "recommendedBy": "Wil",
    "notes": "Wil gave me this book for Christmas 2024.",
    "description": "",
    "dateAdded": "2024-12-25"
  },
  {
    "id": "b032",
    "title": "Meditations",
    "author": "Marcus Aurelius",
    "genre": "Philosophy",
    "yearPublished": 180,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "on-hold",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Didn't finish.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b033",
    "title": "Siddhartha",
    "author": "Hermann Hesse",
    "genre": "Fiction",
    "yearPublished": 1922,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "on-hold",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Not sure if finished.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b034",
    "title": "When Things Fall Apart",
    "author": "Pema Chodron",
    "genre": "Philosophy",
    "yearPublished": 1997,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "on-hold",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Not sure if finished.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b035",
    "title": "The First and Last Freedom",
    "author": "Jiddu Krishnamurti",
    "genre": "Philosophy",
    "yearPublished": 1954,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "on-hold",
    "datePurchased": "2004-01-01",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "With intro from Aldous Huxley. Bought in 2004.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b036",
    "title": "Freedom from the Known",
    "author": "Jiddu Krishnamurti",
    "genre": "Philosophy",
    "yearPublished": 1969,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (Used)",
    "status": "up-next",
    "datePurchased": "2025-01-01",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Purchased Jan 2025. Eastern philosophy/spirituality.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b037",
    "title": "The Mind-Body Problem",
    "author": "Rebecca Goldstein",
    "genre": "Novel",
    "yearPublished": 1983,
    "pageCount": null,
    "coverImage": "",
    "format": "Digital/Kindle",
    "status": "up-next",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Patrick Collison",
    "notes": "Recommended by Patrick Collison.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b038",
    "title": "Wild company",
    "author": "Mel Ziegler",
    "genre": "Non-Fiction",
    "yearPublished": 2012,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL25394088M-M.jpg",
    "format": "Digital/Kindle",
    "status": "up-next",
    "datePurchased": "2025-03-01",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Rick Rubin",
    "notes": "Heard Mel Ziegler on Rick Rubin's podcast. March 2025.",
    "description": "",
    "dateAdded": "2025-03-01"
  },
  {
    "id": "b039",
    "title": "The 5 Types of Wealth",
    "author": "Sahil Bloom",
    "genre": "Self-Help",
    "yearPublished": 2025,
    "pageCount": null,
    "coverImage": "",
    "format": "Audiobook",
    "status": "up-next",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "Bill Ackman",
    "notes": "Bill Ackman highly recommends.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b040",
    "title": "The River of Doubt",
    "author": "Candace Millard",
    "genre": "History",
    "yearPublished": 2005,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "up-next",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b041",
    "title": "Never Split the Difference",
    "author": "Chris Voss",
    "genre": "Business",
    "yearPublished": 2016,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "up-next",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b042",
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "genre": "Psychology",
    "yearPublished": 2011,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "up-next",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b043",
    "title": "The 48 Laws of Power",
    "author": "Robert Greene",
    "genre": "Business",
    "yearPublished": 1998,
    "pageCount": null,
    "coverImage": "",
    "format": "Audiobook",
    "status": "up-next",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Started listening.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b044",
    "title": "Mary Shelley's Frankenstein; or, the Modern Prometheus (1818 text)",
    "author": "Mary Shelley",
    "genre": "Fiction",
    "yearPublished": 1818,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL6147070M-M.jpg",
    "format": "Digital/Kindle",
    "status": "up-next",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b045",
    "title": "The Hunters",
    "author": "James Salter",
    "genre": "Fiction",
    "yearPublished": 1956,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "up-next",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b046",
    "title": "The Autobiography of Benvenuto Cellini",
    "author": "Benvenuto Cellini",
    "genre": "Biography",
    "yearPublished": 1728,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "up-next",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b047",
    "title": "Elon Musk",
    "author": "Walter Isaacson",
    "genre": "Biography",
    "yearPublished": 2023,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "up-next",
    "datePurchased": "2023-10-01",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [
      "gifted to me",
      "donated"
    ],
    "recommendedBy": "Gibran",
    "notes": "Gifted by Gibran for birthday 2023. Donated to Goodwill 2025.",
    "description": "",
    "dateAdded": "2023-10-01"
  },
  {
    "id": "b048",
    "title": "Greenlights",
    "author": "Matthew McConaughey",
    "genre": "Biography",
    "yearPublished": 2020,
    "pageCount": null,
    "coverImage": "",
    "format": "Audiobook",
    "status": "wishlist",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": null,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Buy on audio since Matthew M reads it.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b049",
    "title": "100 Years of Solitude",
    "author": "Gabriel Garcia Marquez",
    "genre": "Fiction",
    "yearPublished": 1967,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b050",
    "title": "On the Road",
    "author": "Jack Kerouac",
    "genre": "Fiction",
    "yearPublished": 1957,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b051",
    "title": "Do Androids Dream of Electric Sheep?",
    "author": "Philip K. Dick",
    "genre": "Fiction",
    "yearPublished": 1968,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b052",
    "title": "The Hitchhiker's Guide to the Galaxy",
    "author": "Douglas Adams",
    "genre": "Fiction",
    "yearPublished": 1979,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b053",
    "title": "Harry Potter and the Sorcerer's Stone",
    "author": "J.K. Rowling",
    "genre": "Fiction",
    "yearPublished": 1997,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b054",
    "title": "Jurassic Park",
    "author": "Michael Crichton",
    "genre": "Fiction",
    "yearPublished": 1990,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b055",
    "title": "Kitchen Confidential",
    "author": "Anthony Bourdain",
    "genre": "Biography",
    "yearPublished": 2000,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 5,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b056",
    "title": "Born to Run",
    "author": "Bruce Springsteen",
    "genre": "Biography",
    "yearPublished": 2016,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b057",
    "title": "Chronicles",
    "author": "Bob Dylan",
    "genre": "Biography",
    "yearPublished": 2004,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL7928173M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b058",
    "title": "The Storyteller",
    "author": "Dave Grohl",
    "genre": "Biography",
    "yearPublished": 2021,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b059",
    "title": "The Razor's Edge",
    "author": "W. Somerset Maugham",
    "genre": "Fiction",
    "yearPublished": 1944,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b060",
    "title": "Of Human Bondage",
    "author": "W. Somerset Maugham",
    "genre": "Fiction",
    "yearPublished": 1915,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b061",
    "title": "The Moon and Sixpence",
    "author": "W. Somerset Maugham",
    "genre": "Fiction",
    "yearPublished": 1919,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b062",
    "title": "Walden",
    "author": "Henry David Thoreau",
    "genre": "Philosophy",
    "yearPublished": 1854,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b063",
    "title": "Gabriel Garcias Marquez's Love In The Time Of Cholera",
    "author": "Harold Bloom",
    "genre": "Fiction",
    "yearPublished": 2005,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL8159838M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b064",
    "title": "The Power of Now",
    "author": "Eckhart Tolle",
    "genre": "Philosophy",
    "yearPublished": 1997,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b065",
    "title": "The Road Less Traveled",
    "author": "M. Scott Peck",
    "genre": "Self-Help",
    "yearPublished": 1978,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b066",
    "title": "Deep and Simple",
    "author": "Bo Lozoff",
    "genre": "Philosophy",
    "yearPublished": 1999,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b067",
    "title": "It's A Meaningful Life",
    "author": "Bo Lozoff",
    "genre": "Philosophy",
    "yearPublished": 2000,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b068",
    "title": "We're All Doing Time",
    "author": "Bo Lozoff",
    "genre": "Philosophy",
    "yearPublished": 1985,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b069",
    "title": "Be Here Now",
    "author": "Ram Dass",
    "genre": "Philosophy",
    "yearPublished": 1971,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b070",
    "title": "The Only Dance There Is",
    "author": "Ram Dass",
    "genre": "Philosophy",
    "yearPublished": 1974,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b071",
    "title": "The Tao of Physics",
    "author": "Fritjof Capra",
    "genre": "Philosophy",
    "yearPublished": 1975,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b072",
    "title": "The World is Flat",
    "author": "Thomas Friedman",
    "genre": "Non-Fiction",
    "yearPublished": 2005,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b073",
    "title": "Brain Droppings",
    "author": "George Carlin",
    "genre": "Humor",
    "yearPublished": 1997,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b074",
    "title": "Napalm & Silly Putty",
    "author": "George Carlin",
    "genre": "Humor",
    "yearPublished": 2001,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b075",
    "title": "Outliers",
    "author": "Malcolm Gladwell",
    "genre": "Non-Fiction",
    "yearPublished": 2008,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "F*ck Malcolm Gladwell. Turns out he's a lying creep.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b076",
    "title": "Being Digital",
    "author": "Nicholas Negroponte",
    "genre": "Technology",
    "yearPublished": 1995,
    "pageCount": null,
    "coverImage": "https://m.media-amazon.com/images/I/81CAWwCJBtL._SL1500_.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b077",
    "title": "Adrift: Seventy-six Days Lost at Sea",
    "author": "Steven Callahan",
    "genre": "Non-Fiction",
    "yearPublished": 1986,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "76 days lost at sea.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b078",
    "title": "The Bell Jar",
    "author": "Sylvia Plath",
    "genre": "Fiction",
    "yearPublished": 1963,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b079",
    "title": "Feel the fear and do it anyway",
    "author": "Susan J. Jeffers",
    "genre": "Self-Help",
    "yearPublished": 1987,
    "pageCount": null,
    "coverImage": "https://m.media-amazon.com/images/I/514o8TOEmKL._SY445_SX342_QL70_FMwebp_.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b080",
    "title": "Light My Fire",
    "author": "Ray Manzarek",
    "genre": "Biography",
    "yearPublished": 1998,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b081",
    "title": "No One Here Gets Out Alive",
    "author": "Danny Sugarman",
    "genre": "Biography",
    "yearPublished": 1980,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b082",
    "title": "Reckless",
    "author": "Chrissie Hynde",
    "genre": "Biography",
    "yearPublished": 2015,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL27185915M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 5,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b083",
    "title": "Corn flakes with John Lennon",
    "author": "Robert Hilburn",
    "genre": "Biography",
    "yearPublished": 2009,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL23971312M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b084",
    "title": "Critical Path",
    "author": "Buckminster Fuller",
    "genre": "Non-Fiction",
    "yearPublished": 1981,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b085",
    "title": "Art and Physics",
    "author": "Leonard Shlain",
    "genre": "Non-Fiction",
    "yearPublished": 1991,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b086",
    "title": "Palimpsest",
    "author": "Gore Vidal",
    "genre": "Biography",
    "yearPublished": 1995,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b087",
    "title": "The Gilded Gutter Life of Francis Bacon",
    "author": "Daniel Farson",
    "genre": "Biography",
    "yearPublished": 1993,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b088",
    "title": "The Wild Boys",
    "author": "William Burroughs",
    "genre": "Fiction",
    "yearPublished": 1971,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b089",
    "title": "The Wild Geese",
    "author": "Daniel Carney",
    "genre": "Fiction",
    "yearPublished": 1977,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b090",
    "title": "Spook Country",
    "author": "William Gibson",
    "genre": "Fiction",
    "yearPublished": 2007,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "Read in 2007.",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b091",
    "title": "2010: Odyssey Two",
    "author": "Arthur C. Clarke",
    "genre": "Fiction",
    "yearPublished": 1982,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b092",
    "title": "Disclosure",
    "author": "Michael Crichton",
    "genre": "Fiction",
    "yearPublished": 1994,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b093",
    "title": "Stickin'",
    "author": "James Carville",
    "genre": "Non-Fiction",
    "yearPublished": 2000,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL7722378M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b094",
    "title": "Buck Up, Suck Up",
    "author": "James Carville & Paul Begala",
    "genre": "Non-Fiction",
    "yearPublished": 2001,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b095",
    "title": "Winning the Future",
    "author": "Newt Gingrich",
    "genre": "Non-Fiction",
    "yearPublished": 2005,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b096",
    "title": "My Life",
    "author": "Bill Clinton",
    "genre": "Biography",
    "yearPublished": 2004,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "b097",
    "title": "The Five Stages of the Soul",
    "author": "Harry Moody",
    "genre": "Philosophy",
    "yearPublished": 1997,
    "pageCount": null,
    "coverImage": "",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 4,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2025-01-01"
  },
  {
    "id": "bmlrj2i1hm88s",
    "title": "Angel",
    "author": "Jason Calacanis",
    "genre": "",
    "yearPublished": 2017,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL28679528M-M.jpg",
    "format": "Audiobook",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2026-02-18"
  },
  {
    "id": "bmlrj3u97qw25",
    "title": "Crushing it!",
    "author": "Gary Vaynerchuk",
    "genre": "Business",
    "yearPublished": 2018,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL27351654M-M.jpg",
    "format": "Audiobook",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2026-02-18"
  },
  {
    "id": "bmlrj6it3iuwx",
    "title": "MONEY Master the Game",
    "author": "Tony Robbins",
    "genre": "Money",
    "yearPublished": null,
    "pageCount": null,
    "coverImage": "https://m.media-amazon.com/images/I/91S7IaFislL._SL1500_.jpg",
    "format": "Audiobook",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 3,
    "favorite": false,
    "tags": [],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2026-02-18"
  },
  {
    "id": "bmlrkbythoatc",
    "title": "Margret & H.A. Rey's Curious George's pop-up storybook house",
    "author": "Willabel L. Tong",
    "genre": "Classics",
    "yearPublished": 1999,
    "pageCount": null,
    "coverImage": "https://covers.openlibrary.org/b/olid/OL396025M-M.jpg",
    "format": "Physical (New)",
    "status": "finished",
    "datePurchased": "",
    "dateStarted": "",
    "dateCompleted": "",
    "currentPage": null,
    "rating": 5,
    "favorite": false,
    "tags": [
      "Wil was the Art and Creative Director"
    ],
    "recommendedBy": "",
    "notes": "",
    "description": "",
    "dateAdded": "2026-02-18"
  }
];
